spring:
  application:
    name: start

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: localhost
    port: 6379

  profiles:
    active: local



jwt:
  secret: fa1acbe22069135dff79f99cc053f9ce3b698834688f33fb36ffd184e8a6ec46
